// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"entgo.io/bug/ent/migrate"

	"entgo.io/bug/ent/hierarchy"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Hierarchy is the client for interacting with the Hierarchy builders.
	Hierarchy *HierarchyClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Hierarchy = NewHierarchyClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Hierarchy: NewHierarchyClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Hierarchy: NewHierarchyClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Hierarchy.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Hierarchy.Use(hooks...)
}

// HierarchyClient is a client for the Hierarchy schema.
type HierarchyClient struct {
	config
}

// NewHierarchyClient returns a client for the Hierarchy from the given config.
func NewHierarchyClient(c config) *HierarchyClient {
	return &HierarchyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hierarchy.Hooks(f(g(h())))`.
func (c *HierarchyClient) Use(hooks ...Hook) {
	c.hooks.Hierarchy = append(c.hooks.Hierarchy, hooks...)
}

// Create returns a create builder for Hierarchy.
func (c *HierarchyClient) Create() *HierarchyCreate {
	mutation := newHierarchyMutation(c.config, OpCreate)
	return &HierarchyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Hierarchy entities.
func (c *HierarchyClient) CreateBulk(builders ...*HierarchyCreate) *HierarchyCreateBulk {
	return &HierarchyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Hierarchy.
func (c *HierarchyClient) Update() *HierarchyUpdate {
	mutation := newHierarchyMutation(c.config, OpUpdate)
	return &HierarchyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HierarchyClient) UpdateOne(h *Hierarchy) *HierarchyUpdateOne {
	mutation := newHierarchyMutation(c.config, OpUpdateOne, withHierarchy(h))
	return &HierarchyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HierarchyClient) UpdateOneID(id int) *HierarchyUpdateOne {
	mutation := newHierarchyMutation(c.config, OpUpdateOne, withHierarchyID(id))
	return &HierarchyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Hierarchy.
func (c *HierarchyClient) Delete() *HierarchyDelete {
	mutation := newHierarchyMutation(c.config, OpDelete)
	return &HierarchyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *HierarchyClient) DeleteOne(h *Hierarchy) *HierarchyDeleteOne {
	return c.DeleteOneID(h.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *HierarchyClient) DeleteOneID(id int) *HierarchyDeleteOne {
	builder := c.Delete().Where(hierarchy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HierarchyDeleteOne{builder}
}

// Query returns a query builder for Hierarchy.
func (c *HierarchyClient) Query() *HierarchyQuery {
	return &HierarchyQuery{
		config: c.config,
	}
}

// Get returns a Hierarchy entity by its id.
func (c *HierarchyClient) Get(ctx context.Context, id int) (*Hierarchy, error) {
	return c.Query().Where(hierarchy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HierarchyClient) GetX(ctx context.Context, id int) *Hierarchy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChild queries the child edge of a Hierarchy.
func (c *HierarchyClient) QueryChild(h *Hierarchy) *HierarchyQuery {
	query := &HierarchyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := h.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(hierarchy.Table, hierarchy.FieldID, id),
			sqlgraph.To(hierarchy.Table, hierarchy.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, hierarchy.ChildTable, hierarchy.ChildPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(h.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a Hierarchy.
func (c *HierarchyClient) QueryParent(h *Hierarchy) *HierarchyQuery {
	query := &HierarchyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := h.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(hierarchy.Table, hierarchy.FieldID, id),
			sqlgraph.To(hierarchy.Table, hierarchy.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, hierarchy.ParentTable, hierarchy.ParentPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(h.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HierarchyClient) Hooks() []Hook {
	return c.hooks.Hierarchy
}
