// +build tools
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo.io/bug/ent/hierarchy"
	"entgo.io/bug/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hierarchyFields := schema.Hierarchy{}.Fields()
	_ = hierarchyFields
	// hierarchyDescSort is the schema descriptor for sort field.
	hierarchyDescSort := hierarchyFields[2].Descriptor()
	// hierarchy.DefaultSort holds the default value on creation for the sort field.
	hierarchy.DefaultSort = hierarchyDescSort.Default.(int)
}
